version: "3.2"
services:
  confluence:
    image: atlassian/confluence-server:6.7.1
    restart: always
    ports:
      - "8090:8090"
    depends_on:
      - db

  db:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=111111
      - POSTGRES_DB=confluencedb
      - POSTGRES_ENCODING=UTF8
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: