FROM mongo
RUN mkdir -p /data/db
COPY doc_info_product.json /data/db/doc_info_product.json 
COPY word_sim.json /data/db/word_sim.json
RUN mongod --fork --logpath /var/log/mongodb.log --dbpath /data/db --smallfiles
# COPY importjson.sh /data/db/importjson.sh
# RUN chmod +x /data/db/importjson.sh
# ENTRYPOINT ["/data/db/importjson.sh"]
EXPOSE 27000
VOLUME [ "/data/db" ]
CMD [ "mongod", "--smallfiles"]